config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"
  resource :sessions, only: [:update]

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  get "/register" => "users#new"
  post "/register" => "users#create"
  get "/dashboard" => "users#show"
  patch "/dashboard" => "users#update"
  get "/jokes" => "jokes#index"

  resources :categories, only: [:index]
  resources :items, only: [:index, :show]
  resource :cart, only: [:show, :destroy, :create]
  patch "/cart" => "carts#update"

  post "/checkout" => "orders#create"
  get "/checkout" => "orders#edit"

  namespace :admin do
    get "/dashboard" => "users#show"
    patch "/dashboard" => "users#update"
    get "/orders/:order_id" => "orders#show"
    patch "/orders" => "orders#update"
    resources :items, only: [:index, :new, :update, :edit, :create]
  end

  post "/ajax-joke" => "ajokes#show"

  get "/:category" => "categories#show"

end

app/models/cart_item.rb
class CartItem < SimpleDelegator
  attr_reader :quantity, :item
  
  def initialize(item, quantity)
    @quantity = quantity
    @item = Item.find_by_dao(item)
    super(@item)
  end

  def total
    price * @quantity
  end

  def to_param
    @item.id
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
  validates :name, :dao, presence: true
  validates :name, uniqueness: true

  before_validation do
    if name
      self.dao = name.downcase.gsub(" ", "")
    end
  end

  def to_param
    dao
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  validates :name, :description, :image_url, :dao, :price, presence: true
  validates :name, uniqueness: true
  validates :price, numericality: true

  before_validation :establish_daoism, :establish_image_url
  def establish_daoism
    if name
      self.dao = name.downcase.gsub(" ", "")
    end
  end

  def to_param
    dao
  end

  def establish_image_url
    if image_url.blank?
      self.image_url = "http://i.imgur.com/yJfmkeK.png"
    end
  end
end

app/models/joke.rb
class Joke < ActiveRecord::Base
  validates :lead, :punchline, uniqueness: true, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items

  validates :user_id, :status, presence: true

  def total
    order_items.sum(:subtotal)
  end

  def quantity
    order_items.sum(:quantity)
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :joke
  belongs_to :order
  before_save :fill_subtotal

  validates :item_id, :joke_id, :quantity,  presence: true
  def total
    if item && quantity
      quantity * item.price
    else
      0
    end
  end

  def fill_subtotal
    self.subtotal = total
  end
end

app/models/session_handler.rb
class SessionHandler

  def initialize(session)
    @session = session
  end

  def add_cart_item(item)
    @item = item
    if order_item_in_session
      increment_order_item_quantity
    else
      ensure_joke
      create_a_new_order_item
    end
  end

  def increment_order_item_quantity
    OrderItem.increment_counter(:quantity, order_item_in_session.id)
  end

  def ensure_joke
      @session[:joke_id] ||= Joke.all.sample.id
  end

  def create_a_new_order_item
    order_item = OrderItem.create(item_id: @item.id,
                                  joke_id: @session[:joke_id], quantity: 1)
    @session[:cart] << order_item.id
  end

  def order_item_in_session
    if @session[:cart]
      OrderItem.where(id: @session[:cart], joke_id: @session[:joke_id], item_id: @item.id).first
    else
      @session[:cart] = []
      false
    end
  end

  def remove_cart_item(order_item)
    @session[:cart].delete(order_item.id)
    order_item.destroy
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, :user_name, presence: true
  validates :email, uniqueness: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates_confirmation_of :password
  
  has_many :orders
end

app/controllers/ajokes_controller.rb
class AjokesController < ApplicationController
  def show
    respond_to do |format|
      format.js 
      format.html {render text: "hi"}
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def create
    item = Item.find_by_dao(params[:item_id])

    session_handler = SessionHandler.new(session)
    session_handler.add_cart_item(item)

    flash[:notice] = 'Added ' + item.name
    redirect_to cart_path
  end

  def show
    @order_items = OrderItem.where(id: session[:cart])
    @cart_total = @order_items.sum(:subtotal)
    @user = current_user
    session[:target_page] = '/cart'
  end

  def update
    order_item = OrderItem.find(params[:order_item][:order_item_id])
    if new_quantity > 0
      order_item.update(quantity: new_quantity)
      flash[:notice] = "Quantity updated"
    else
      SessionHandler.new(session).remove_cart_item(order_item)
      flash[:notice] = "Successfully removed <a href=\"/items/#{order_item.item.dao}\">#{order_item.item.name}</a> from your cart."
    end
    redirect_to cart_path
  end

  def destroy
    OrderItem.where(id: session[:cart]).destroy_all
    session.delete(:cart)
    flash[:notice] = "Cart deleted!"
    redirect_to cart_path
  end

  private

    def new_quantity
      if params[:commit] == "Update Quantity"
        params[:order_item][:quantity].to_i
      elsif params[:commit] == "Remove"
        0
      end
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all.order(:name)
    @random_joke = Joke.all.sample
  end

  def show
    @item = Item.find_by_dao(params[:id])
  end
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  def index
    @jokes = Joke.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    if current_user
      @orders = current_user.orders
      @user = current_user
    else
      flash[:notice] = "Please login before trying to view your account information."
      redirect_to root_path
    end
  end

  def create
    user = User.new(new_user_params)
    if user.save
      session[:user] = user.id
      flash[:notice] = 'user successfully created'
      redirect_to dashboard_path
    else
      flash[:alert] = user.errors.full_messages.first
      redirect_to action: 'new'
    end
  end

  def update
    current_user.update(update_user_params)
    current_user.save
    flash[:notice] = "You have successfully updated your information!"
    redirect_to dashboard_path
  end

  private

  def new_user_params
    params.require(:user).permit(:email, :user_name, :password,
      :password_confirmation, :first, :last, :street, :city, :state, :zip)
  end

  def update_user_params
    params.require(:user).permit(:email, :user_name, :first, :last, :street,
      :city, :state, :zip)
  end
end

app/helpers/ajokes_helper.rb
module AjokesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ajokes/show.js.erb
<% @joke = Joke.all.sample %>
$(".hit-me-response").html("<h2><%= @joke.lead  %><h2><h2><%= @joke.punchline  %><h2>")

var voices = window.speechSynthesis.getVoices();
var msg1 = new SpeechSynthesisUtterance("<%= raw(@joke.lead) %>");
var msg2 = new SpeechSynthesisUtterance("<%= raw(@joke.punchline) %>");
msg1.voice = voices[10]
    window.speechSynthesis.speak(msg1);

msg2.voice = voices[10]
    window.speechSynthesis.speak(msg2);

app/views/carts/_cart.html.erb
<table class='table table-striped'>
  <thead>
    <tr><th></th><th>Item</th><th class="text-center">Quantity</th><th class="text-right">Unit Price</th><th class="text-right">Totals</th></tr>
  </thead>
  <tbody>
    <% @order_items.each do |order_item| %>

      <%= form_for :order_item, action: cart_path, method: :patch do |f| %>
      <tr class="cart-row">
        <td class="tiny"><%= link_to image_tag(order_item.item.image_url, class: "img-responsive"), order_item.item %></td>
          <td><%= link_to order_item.item.name, order_item.item %></td>
        <td class="">
          <%= f.text_field :quantity, value: order_item.quantity, class: "form-control input-xs dad-quantity" %>
          <%= f.hidden_field :order_item_id, value: order_item.id %>

          <%= f.submit "Update Quantity", class: "btn btn-xs btn-success" %>
          <%= f.submit "Remove", class: "btn btn-xs btn-danger" %>
          <% end %>
        </td>
        <td class='cart-price'><span class='cart-price'><%= number_to_currency(order_item.item.price) %></span></td>
        <td class='cart-price'><span class='cart-price'><%= number_to_currency(order_item.total) %></span></td>
      </tr>
      <tr>
        <td colspan="5" class="dad-item-joke-separator text-center"><%= order_item.joke.lead %></td>
      </tr>
    <% end %>
  </tbody>
   <tfoot class='grand-total-row'>
    <td>Total:</td>
    <td></td>
    <td></td>
    <td></td>
    <td class='price'><%= number_to_currency(@cart_total) %></td>
  </tfoot>
</table>

<div class="text-right">
  <%= link_to "Delete Cart", cart_path, id: "delete", method: :delete, class: "btn btn-warning" %>
</div>

app/views/carts/_empty_cart.html.erb
<div class="empty_cart">
  There are no items in your cart. Get to the shopping!
</div>

app/views/carts/show.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='panel'>
      <div class='panel-body'>
        <h1 class='text-left'>Your Cart</h1>
      </div>
    </div>
  </div>
</div>
<div class="row">
<div class="col-md-7">
  <div class='panel panel-default'>
    <div class='panel-body'>
      <% if !@order_items.empty? %>
      <%= render 'cart' %>
      <% else %>
      <%= render 'empty_cart' %>
      <% end %>
    </div>
  </div>

</div>

<div class="col-md-5">
  <div class='panel panel-default'>
    <div class='panel-body cart-right'>
      <% if @user %>
        <%= render partial: 'users/shipping_info' %>
        <% if session[:cart] %><br>
          <%= button_to "Checkout", checkout_path,
                               method: :post, data: { confirm: "Are you sure?" },
                               class: "form-control btn btn-primary btn-md dad-checkout-btn" %>
        <% end %>
      <% else %>
        <p class="text-center">Please login before checking out.</p>
        <br>
        <%= link_to "Login", '/login',  class: "form-control btn btn-primary btn-md" %><br>
      <% end %>
    </div>
  </div>
</div>

</div>