config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"
  resource :sessions, only: [:update]

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  get "/register" => "users#new"
  post "/register" => "users#create"
  get "/dashboard" => "users#show"
  patch "/dashboard" => "users#update"
  get "/jokes" => "jokes#index"

  resources :categories, only: [:index]
  resources :items, only: [:index, :show]
  resource :cart, only: [:show, :destroy, :create]
  patch "/cart" => "carts#update"

  post "/checkout" => "orders#create"
  get "/checkout" => "orders#edit"

  namespace :admin do
    get "/dashboard" => "users#show"
    patch "/dashboard" => "users#update"
    get "/orders/:order_id" => "orders#show"
    patch "/orders" => "orders#update"
    resources :items, only: [:index, :new, :update, :edit, :create]
  end

  post "/ajax-joke" => "ajokes#show"

  get "/:category" => "categories#show"

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  validates :name, :description, :image_url, :dao, :price, presence: true
  validates :name, uniqueness: true
  validates :price, numericality: true

  before_validation :establish_daoism, :establish_image_url
  def establish_daoism
    if name
      self.dao = name.downcase.gsub(" ", "")
    end
  end

  def to_param
    dao
  end

  def establish_image_url
    if image_url.blank?
      self.image_url = "http://i.imgur.com/yJfmkeK.png"
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::AdminController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @categories = Category.all
  end

  def update
    dao = params[:id]
    item = Item.find_by_dao(dao)
    if item.update(item_params)
      flash[:notice] = "Item successfully updated!"
      redirect_to admin_items_path
    else
      flash[:notice] = item.errors.full_messages
      redirect_to "/admin/items/#{dao}/edit"
    end
  end

  def edit
    @item = Item.find_by_dao(params[:id])
    @categories = Category.all
  end

  def create
    item = Item.new(item_params)
    if item.save
      flash[:notice] = "New item '#{item.name}' created."
      redirect_to admin_items_path
    else
      flash[:notice] = item.errors.full_messages
      redirect_to new_admin_item_path
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :image_url,
                                 :category_id, :price, :status)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all.order(:name)
    @random_joke = Joke.all.sample
  end

  def show
    @item = Item.find_by_dao(params[:id])
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.erb
<div class="col-md-4 text-center">
  <div class="dad-item panel panel-default">
    <div class="panel-body">
      <%= render partial: "partials/link_summary", locals: {summary: item} %><br>
      <span class='price'><%= number_to_currency(item.price) %></span> <br>
      <span class='add_to_cart_button'><%= button_to "Add To Cart", cart_path(item_id: item), class:'btn btn-primary' %></span>
    </div>
  </div>
</div>

app/views/items/_item_show.html.erb
<div class="col-md-4 text-center">
  <div class="dad-item panel panel-default">
    <div class="panel-body">
      <%= render partial: "partials/link_summary", locals: {summary: @item} %><br>
      <span class='price'><%= number_to_currency(@item.price) %></span> <br>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='panel'>
      <div class='panel-body'>
        <h1>All Products</h1>
      </div>
    </div>
  </div>
</div>

<div class="row text-center">
  <%= render @items %>
</div>

app/views/items/show.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='panel'>
      <div class='panel-body'>
        <h1><%= @item.name %></h1>
      </div>
    </div>
  </div>
</div>


<div class="row">
  <%= render "item_show", locals: {item: @item} %>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <h2>Description</h2>
        <p><%= @item.description %></p>
        <span class='add_to_cart_button'><%= button_to "Add To Cart", cart_path(item_id: @item), class:'btn btn-primary' %></span>
      </div>
    </div>
  </div>
</div>



<div class="row">
  <div class='col-md-12'>
    <div class='panel panel-default'>
      <div class='panel-body'>
        <h2>Comments: </h2>

      </div>
    </div>

  </div>
</div>

<div class="row">
  <div class='col-md-12'>
    <div class='panel panel-default'>
      <div class='panel-body'>
        <div class="col-md-1">
          <%= image_tag('richard.jpg', class: "img-responsive") %>
        </div>
        <div class="col-md-11">
          <br>
          <p class='dad-testimonial'>Seemed like a steep price at first but worth every penny!</p>
          <p>- Richard</p>
        </div>

      </div>
    </div>

  </div>
</div>