config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"
  resource :sessions, only: [:update]

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  get "/register" => "users#new"
  post "/register" => "users#create"
  get "/dashboard" => "users#show"
  patch "/dashboard" => "users#update"
  get "/jokes" => "jokes#index"

  resources :categories, only: [:index]
  resources :items, only: [:index, :show]
  resource :cart, only: [:show, :destroy, :create]
  patch "/cart" => "carts#update"

  post "/checkout" => "orders#create"
  get "/checkout" => "orders#edit"

  namespace :admin do
    get "/dashboard" => "users#show"
    patch "/dashboard" => "users#update"
    get "/orders/:order_id" => "orders#show"
    patch "/orders" => "orders#update"
    resources :items, only: [:index, :new, :update, :edit, :create]
  end

  post "/ajax-joke" => "ajokes#show"

  get "/:category" => "categories#show"

end

app/models/cart_item.rb
class CartItem < SimpleDelegator
  attr_reader :quantity, :item
  
  def initialize(item, quantity)
    @quantity = quantity
    @item = Item.find_by_dao(item)
    super(@item)
  end

  def total
    price * @quantity
  end

  def to_param
    @item.id
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
  validates :name, :dao, presence: true
  validates :name, uniqueness: true

  before_validation do
    if name
      self.dao = name.downcase.gsub(" ", "")
    end
  end

  def to_param
    dao
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  validates :name, :description, :image_url, :dao, :price, presence: true
  validates :name, uniqueness: true
  validates :price, numericality: true

  before_validation :establish_daoism, :establish_image_url
  def establish_daoism
    if name
      self.dao = name.downcase.gsub(" ", "")
    end
  end

  def to_param
    dao
  end

  def establish_image_url
    if image_url.blank?
      self.image_url = "http://i.imgur.com/yJfmkeK.png"
    end
  end
end

app/models/joke.rb
class Joke < ActiveRecord::Base
  validates :lead, :punchline, uniqueness: true, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items

  validates :user_id, :status, presence: true

  def total
    order_items.sum(:subtotal)
  end

  def quantity
    order_items.sum(:quantity)
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :joke
  belongs_to :order
  before_save :fill_subtotal

  validates :item_id, :joke_id, :quantity,  presence: true
  def total
    if item && quantity
      quantity * item.price
    else
      0
    end
  end

  def fill_subtotal
    self.subtotal = total
  end
end

app/models/session_handler.rb
class SessionHandler

  def initialize(session)
    @session = session
  end

  def add_cart_item(item)
    @item = item
    if order_item_in_session
      increment_order_item_quantity
    else
      ensure_joke
      create_a_new_order_item
    end
  end

  def increment_order_item_quantity
    OrderItem.increment_counter(:quantity, order_item_in_session.id)
  end

  def ensure_joke
      @session[:joke_id] ||= Joke.all.sample.id
  end

  def create_a_new_order_item
    order_item = OrderItem.create(item_id: @item.id,
                                  joke_id: @session[:joke_id], quantity: 1)
    @session[:cart] << order_item.id
  end

  def order_item_in_session
    if @session[:cart]
      OrderItem.where(id: @session[:cart], joke_id: @session[:joke_id], item_id: @item.id).first
    else
      @session[:cart] = []
      false
    end
  end

  def remove_cart_item(order_item)
    @session[:cart].delete(order_item.id)
    order_item.destroy
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, :user_name, presence: true
  validates :email, uniqueness: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates_confirmation_of :password
  
  has_many :orders
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  def show
    @user = current_user
    @orders = current_user.orders
    @all_orders = Order.all.order(created_at: :desc).
    paginate(:page => params[:page], :per_page => 40)
  end

  def update
  end
end

app/controllers/ajokes_controller.rb
class AjokesController < ApplicationController
  def show
    respond_to do |format|
      format.js 
      format.html {render text: "hi"}
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def create
    item = Item.find_by_dao(params[:item_id])

    session_handler = SessionHandler.new(session)
    session_handler.add_cart_item(item)

    flash[:notice] = 'Added ' + item.name
    redirect_to cart_path
  end

  def show
    @order_items = OrderItem.where(id: session[:cart])
    @cart_total = @order_items.sum(:subtotal)
    @user = current_user
    session[:target_page] = '/cart'
  end

  def update
    order_item = OrderItem.find(params[:order_item][:order_item_id])
    if new_quantity > 0
      order_item.update(quantity: new_quantity)
      flash[:notice] = "Quantity updated"
    else
      SessionHandler.new(session).remove_cart_item(order_item)
      flash[:notice] = "Successfully removed <a href=\"/items/#{order_item.item.dao}\">#{order_item.item.name}</a> from your cart."
    end
    redirect_to cart_path
  end

  def destroy
    OrderItem.where(id: session[:cart]).destroy_all
    session.delete(:cart)
    flash[:notice] = "Cart deleted!"
    redirect_to cart_path
  end

  private

    def new_quantity
      if params[:commit] == "Update Quantity"
        params[:order_item][:quantity].to_i
      elsif params[:commit] == "Remove"
        0
      end
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all.order(:name)
    @random_joke = Joke.all.sample
  end

  def show
    @item = Item.find_by_dao(params[:id])
  end
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  def index
    @jokes = Joke.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    order = Order.create(status: "ordered", user_id: session[:user])
    order.order_items << OrderItem.where(id: session[:cart])
    session.delete(:cart)
    flash[:notice] = "Thank you for your order!"
    redirect_to dashboard_path
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    if current_user
      @orders = current_user.orders
      @user = current_user
    else
      flash[:notice] = "Please login before trying to view your account information."
      redirect_to root_path
    end
  end

  def create
    user = User.new(new_user_params)
    if user.save
      session[:user] = user.id
      flash[:notice] = 'user successfully created'
      redirect_to dashboard_path
    else
      flash[:alert] = user.errors.full_messages.first
      redirect_to action: 'new'
    end
  end

  def update
    current_user.update(update_user_params)
    current_user.save
    flash[:notice] = "You have successfully updated your information!"
    redirect_to dashboard_path
  end

  private

  def new_user_params
    params.require(:user).permit(:email, :user_name, :password,
      :password_confirmation, :first, :last, :street, :city, :state, :zip)
  end

  def update_user_params
    params.require(:user).permit(:email, :user_name, :first, :last, :street,
      :city, :state, :zip)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/ajokes_helper.rb
module AjokesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/users/_order.html.erb
<tr class='dad-admin-order-table dad-<%= order.status %>-status'>
  <td><%= link_to order.id, admin_path(order) %></td>
  <td><%= order.created_at.strftime("%m/%d/%Y")%></td>
  <td><%= order.user.first %> <%= order.user.last %></td>
  <td><%= order.quantity %></td>
  <td><%= number_to_currency(order.total) %></td>
  <td><%= order.status %></td>
  <td><%= button_to "ordered", admin_orders_path, method: :patch, params: { order_id: order.id, new_status: "ordered" }, class: "btn btn-xs btn-warning inline" %> <%= button_to "paid", admin_orders_path, method: :patch, params: { order_id: order.id, new_status: "paid" }, class: "btn btn-xs btn-success inline" %> <%= button_to "cancelled", admin_orders_path, method: :patch, params: { order_id: order.id, new_status: "cancelled" }, class: "btn btn-xs btn-danger inline" %> <%= button_to "completed", admin_orders_path, method: :patch, params: { order_id: order.id, new_status: "completed" }, class: "btn btn-xs btn-primary inline" %></td>
</tr>

app/views/admin/users/show.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='panel'>
      <div class='panel-body'>
        <h1>Admin Dashboard</h1>
        <%= link_to "Manage Items", admin_items_path, class: "btn btn-primary", style: "float: right;" %>
      </div>
    </div>
  </div>
</div>

<div class="panel">
    <div class="page_info">
      <h3 class="text-center"><%= page_entries_info @all_orders %></h3>
    </div>
      <h3 class="text-center"><%= will_paginate @all_orders, :container => false %></h3>
</div>

<div class='row text-center'>
  <div class='col-md-3'>
    <div class='panel'>
      <div class='panel-body dad-filter dad-ordered-filter'>
        <h2>Ordered</h2>
          <h2><%= status_total("ordered") %></h2>
      </div>
    </div>
  </div>

  <div class='col-md-3'>
    <div class='panel'>
      <div class='panel-body dad-filter dad-paid-filter'>
        <h2>Paid</h2>
        <h2><%= status_total("paid") %></h2>
      </div>
    </div>
  </div>

  <div class='col-md-3'>
    <div class='panel'>
      <div class='panel-body dad-filter dad-cancelled-filter'>
        <h2>Cancelled</h2>
        <h2><%= status_total("cancelled") %></h2>
      </div>
    </div>
  </div>

  <div class='col-md-3'>
    <div class='panel'>
      <div class='panel-body dad-filter dad-completed-filter'>
        <h2>Completed</h2>
        <h2><%= status_total("completed") %></h2>
      </div>
    </div>
  </div>
</div>

<div class='row'>
  <div class='col-md-12'>
    <div class='panel'>
      <div class='panel-body'>
        <h2>All Orders</h2><br>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Order #</th><th>Date</th><th>Customer</th><th>Total Quantity</th><th>Revenue</th><th>Status</th><th>Mark Order As</th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "order", collection: @all_orders %>
          </tbody>
          <tfoot><tr></tr></tfoot>
        </table>
      </div>
    </div>
  </div>
</div>
<%= render "/users/user_info" %>

<script src='https://code.jquery.com/jquery-2.1.4.min.js'></script>
<script>
$(document).ready(function () {
  $('.dad-filter').click(function () {
    $('.dad-admin-order-table').addClass("hidden")
    $('.dad-filter').removeClass("dad-admin-filter-color")


  });

  $('.dad-ordered-filter').click(function () {
      $('.dad-ordered-status').removeClass("hidden")
      $('.dad-ordered-filter').addClass("dad-admin-filter-color")
  });

  $('.dad-paid-filter').click(function () {
      $('.dad-paid-status').removeClass("hidden")
      $('.dad-paid-filter').addClass("dad-admin-filter-color")
  });

  $('.dad-cancelled-filter').click(function () {
      $('.dad-cancelled-status').removeClass("hidden")
      $('.dad-cancelled-filter').addClass("dad-admin-filter-color")
  });

  $('.dad-completed-filter').click(function () {
      $('.dad-completed-status').removeClass("hidden")
      $('.dad-completed-filter').addClass("dad-admin-filter-color")
  });

});



</script>

app/views/users/_order.html.erb
<div class='dad-invoice-heading'><h3>Invoice #<%= order.id %></h3><%= order.created_at.strftime("%B %d, %Y, %H:%M:%S") %></div>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
        <tr><th></th><th class='text-center'>Item</th><th class="text-center">Quantity</th><th class="text-center">Unit Price</th><th class="text-center">Totals</th></tr>
      </thead>
      <tbody>
        <%= render partial: '/users/order_row', collection: order.order_items %>
      </tbody>
      <tfoot class='grand-total-row'>
        <td class='price'>Total:</td>
        <td></td>
        <td></td>
        <td></td>
        <td class='price text-center'><%= number_to_currency(order.total) %></td>
      </tfoot>
    </table>
  </div>
</div>

app/views/users/_order_row.html.erb
<tr class="cart-row">
  <td class="tiny text-center"><%= link_to image_tag(order_row.item.image_url, class: "img-responsive"), order_row.item %></td>
    <td class='text-center'><%= link_to order_row.item.name, order_row.item %></td>
  <td class='text-center'><%= order_row.quantity %></td>
  <td class='cart-price text-center'><span class='cart-price'><%= number_to_currency(order_row.item.price) %></span></td>
  <td class='cart-price text-center'><span class='cart-price'><%= number_to_currency(order_row.total) %></span></td>
</tr>
<tr>
  <td colspan="5" class="dad-item-joke-separator text-center"><%= order_row.joke.lead %></td>
</tr>

app/views/users/_shipping_info.html.erb
<div class="panel-heading text-center">
  Shipping Address
</div>
<div class="panel-body">
  <table class="table">
    <tr>
      <td class="text-right">Address:</td><td><%= @user.street %></td>
    </tr>
  <tr>
      <td class="text-right">city:</td><td><%= @user.city %></td>
  </tr>
  <tr>
      <td class="text-right">state:</td><td><%= @user.state %></td>
  </tr>
  <tr>
      <td class="text-right">zipcode:</td><td><%= @user.zip %></td>
  </tr>
  </table>
</div>

app/views/users/_signup_form.html.erb
<div class='row text-center'>
  <div class='col-md-6 col-centered'>
    <div class='panel'>
      <div class='panel-body text-left'>
        <%= form_for @user, url: register_path, method: :post, html: {class: "signup"} do |f| %>

        <h3>Account Info</h3>
        <%= f.text_field :user_name, placeholder: "Username*", class: "form-control input-md", autofocus: true %><br>

        <%= f.text_field :email, placeholder: "Email*", class: "form-control input-md" %><br>

        <%= f.password_field :password, placeholder: "Password*", class: "form-control input-md" %><br>

        <%= f.password_field :password_confirmation, placeholder: "Confirm Password*", class: "form-control input-md" %><br><br>

        <h3>Shipping Info</h3>
        <%= f.text_field :first, placeholder: "First Name", class: "form-control input-md dad-form-control dad-form-control-left" %>
        <%= f.text_field :last, placeholder: "Last Name", class: "form-control input-md dad-form-control dad-form-control-right" %><br><br>

        <%= f.text_field :street, placeholder: "Street Address", class: "form-control input-md" %><br>
        <%= f.text_field :city, placeholder: "City", class: "form-control input-md dad-form-control dad-form-control-left" %>
        <%= f.select :state, [["Alabama", "AL"], ["Alaska", "AK"], ["Arizona", "AZ"], ["Arkansas", "AR"], ["California", "CA"], ["Colorado", "CO"], ["Connecticut", "CT"], ["Delaware", "DE"], ["District Of Columbia", "DC"], ["Florida", "FL"], ["Georgia", "GA"], ["Hawaii", "HI"], ["Idaho", "ID"], ["Illinois", "IL"], ["Indiana", "IN"], ["Iowa", "IA"], ["Kansas", "KS"], ["Kentucky", "KY"], ["Louisiana", "LA"], ["Maine", "ME"], ["Maryland", "MD"], ["Massachusetts", "MA"], ["Michigan", "MI"], ["Minnesota", "MN"], ["Mississippi", "MS"], ["Missouri", "MO"], ["Montana", "MT"], ["Nebraska", "NE"], ["Nevada", "NV"], ["New Hampshire", "NH"], ["New Jersey", "NJ"], ["New Mexico", "NM"], ["New York", "NY"], ["North Carolina", "NC"], ["North Dakota", "ND"], ["Ohio", "OH"], ["Oklahoma", "OK"], ["Oregon", "OR"], ["Pennsylvania", "PA"], ["Rhode Island", "RI"], ["South Carolina", "SC"], ["South Dakota", "SD"], ["Tennessee", "TN"], ["Texas", "TX"], ["Utah", "UT"], ["Vermont", "VT"], ["Virginia", "VA"], ["Washington", "WA"], ["West Virginia", "WV"], ["Wisconsin", "WI"], ["Wyoming", "WY"]], class: "form-control dad-form-control" %>

        <%= f.text_field :zip, placeholder: "Zip", class: "form-control input-md dad-form-control dad-form-control-small" %><br><br>

        <div class="text-center">
          <%= f.submit "Create Account", class: "btn btn-md btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_update_form.html.erb
<div class='row text-center'>
  <div class='col-md-12 col-centered'>
    <div class='panel'>
      <div class='panel-body'>
        <div class="row">
          <div class="col-md-6">
            <div class=''>
              <div class='panel-body'>
                <%= form_for @user, url: dashboard_path, method: :patch, html: {class: "signup"} do |f| %>

                <h3>Account Info</h3>
                <%= f.text_field :user_name, placeholder: "Username*", class: "form-control input-md" %><br>

                <%= f.text_field :email, placeholder: "Email*", class: "form-control input-md" %><br>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class=''>
              <div class='panel-body text-left'>
                <h3>Shipping Info</h3>
                <%= f.text_field :first, placeholder: "First Name", class: "form-control input-md dad-form-control dad-form-control-left" %>
                <%= f.text_field :last, placeholder: "Last Name", class: "form-control input-md dad-form-control dad-form-control-right" %><br><br>

                <%= f.text_field :street, placeholder: "Street Address", class: "form-control input-md" %><br>
                <%= f.text_field :city, placeholder: "City", class: "form-control input-md dad-form-control dad-form-control-left" %>
                <%= f.select :state, [["Alabama", "AL"], ["Alaska", "AK"], ["Arizona", "AZ"], ["Arkansas", "AR"], ["California", "CA"], ["Colorado", "CO"], ["Connecticut", "CT"], ["Delaware", "DE"], ["District Of Columbia", "DC"], ["Florida", "FL"], ["Georgia", "GA"], ["Hawaii", "HI"], ["Idaho", "ID"], ["Illinois", "IL"], ["Indiana", "IN"], ["Iowa", "IA"], ["Kansas", "KS"], ["Kentucky", "KY"], ["Louisiana", "LA"], ["Maine", "ME"], ["Maryland", "MD"], ["Massachusetts", "MA"], ["Michigan", "MI"], ["Minnesota", "MN"], ["Mississippi", "MS"], ["Missouri", "MO"], ["Montana", "MT"], ["Nebraska", "NE"], ["Nevada", "NV"], ["New Hampshire", "NH"], ["New Jersey", "NJ"], ["New Mexico", "NM"], ["New York", "NY"], ["North Carolina", "NC"], ["North Dakota", "ND"], ["Ohio", "OH"], ["Oklahoma", "OK"], ["Oregon", "OR"], ["Pennsylvania", "PA"], ["Rhode Island", "RI"], ["South Carolina", "SC"], ["South Dakota", "SD"], ["Tennessee", "TN"], ["Texas", "TX"], ["Utah", "UT"], ["Vermont", "VT"], ["Virginia", "VA"], ["Washington", "WA"], ["West Virginia", "WV"], ["Wisconsin", "WI"], ["Wyoming", "WY"]], class: "form-control dad-form-control" %>

                <%= f.text_field :zip, placeholder: "Zip", class: "form-control input-md dad-form-control dad-form-control-small" %><br><br>
              </div>
            </div>
          </div>
          <%= f.submit "Update Info", class: "btn btn-md btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_user_info.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <h1>My Account Information</h1>
      </div>
    </div>
  </div>
</div>

<%= render '/users/update_form' %>

<div class="row">
<div class="col-md-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1>Past Orders</h1>
    </div>
    <div class="panel-body">
      <% if @orders.count > 0 %>
        <%= render partial: "/users/order", collection: @orders %>
      <% else %>
        This account has no order history.
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/users/new.html.erb
<% if session[:user] %>
<div class='row'>
  <div class='col-md-12'>
    <div class='panel'>
      <div class='panel-body'>
        <h1>Please Log out before making a new Account</h1>
      </div>
    </div>
  </div>
</div>
<% else %>
<div class='row'>
  <div class='col-md-6 col-centered'>
    <div class='panel'>
      <div class='panel-body'>
        <h1>Account Creation</h1>
      </div>
    </div>
  </div>
</div>

<%= render 'signup_form' %>

<% end %>

app/views/users/show.html.erb
<%= render 'user_info' %>