config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"
  resource :sessions, only: [:update]

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  get "/register" => "users#new"
  post "/register" => "users#create"
  get "/dashboard" => "users#show"
  patch "/dashboard" => "users#update"
  get "/jokes" => "jokes#index"

  resources :categories, only: [:index]
  resources :items, only: [:index, :show]
  resource :cart, only: [:show, :destroy, :create]
  patch "/cart" => "carts#update"

  post "/checkout" => "orders#create"
  get "/checkout" => "orders#edit"

  namespace :admin do
    get "/dashboard" => "users#show"
    patch "/dashboard" => "users#update"
    get "/orders/:order_id" => "orders#show"
    patch "/orders" => "orders#update"
    resources :items, only: [:index, :new, :update, :edit, :create]
  end

  post "/ajax-joke" => "ajokes#show"

  get "/:category" => "categories#show"

end

app/models/cart_item.rb
class CartItem < SimpleDelegator
  attr_reader :quantity, :item
  
  def initialize(item, quantity)
    @quantity = quantity
    @item = Item.find_by_dao(item)
    super(@item)
  end

  def total
    price * @quantity
  end

  def to_param
    @item.id
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
  validates :name, :dao, presence: true
  validates :name, uniqueness: true

  before_validation do
    if name
      self.dao = name.downcase.gsub(" ", "")
    end
  end

  def to_param
    dao
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  validates :name, :description, :image_url, :dao, :price, presence: true
  validates :name, uniqueness: true
  validates :price, numericality: true

  before_validation :establish_daoism, :establish_image_url
  def establish_daoism
    if name
      self.dao = name.downcase.gsub(" ", "")
    end
  end

  def to_param
    dao
  end

  def establish_image_url
    if image_url.blank?
      self.image_url = "http://i.imgur.com/yJfmkeK.png"
    end
  end
end

app/models/joke.rb
class Joke < ActiveRecord::Base
  validates :lead, :punchline, uniqueness: true, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items

  validates :user_id, :status, presence: true

  def total
    order_items.sum(:subtotal)
  end

  def quantity
    order_items.sum(:quantity)
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :joke
  belongs_to :order
  before_save :fill_subtotal

  validates :item_id, :joke_id, :quantity,  presence: true
  def total
    if item && quantity
      quantity * item.price
    else
      0
    end
  end

  def fill_subtotal
    self.subtotal = total
  end
end

app/models/session_handler.rb
class SessionHandler

  def initialize(session)
    @session = session
  end

  def add_cart_item(item)
    @item = item
    if order_item_in_session
      increment_order_item_quantity
    else
      ensure_joke
      create_a_new_order_item
    end
  end

  def increment_order_item_quantity
    OrderItem.increment_counter(:quantity, order_item_in_session.id)
  end

  def ensure_joke
      @session[:joke_id] ||= Joke.all.sample.id
  end

  def create_a_new_order_item
    order_item = OrderItem.create(item_id: @item.id,
                                  joke_id: @session[:joke_id], quantity: 1)
    @session[:cart] << order_item.id
  end

  def order_item_in_session
    if @session[:cart]
      OrderItem.where(id: @session[:cart], joke_id: @session[:joke_id], item_id: @item.id).first
    else
      @session[:cart] = []
      false
    end
  end

  def remove_cart_item(order_item)
    @session[:cart].delete(order_item.id)
    order_item.destroy
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, :user_name, presence: true
  validates :email, uniqueness: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates_confirmation_of :password
  
  has_many :orders
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def create
    item = Item.find_by_dao(params[:item_id])

    session_handler = SessionHandler.new(session)
    session_handler.add_cart_item(item)

    flash[:notice] = 'Added ' + item.name
    redirect_to cart_path
  end

  def show
    @order_items = OrderItem.where(id: session[:cart])
    @cart_total = @order_items.sum(:subtotal)
    @user = current_user
    session[:target_page] = '/cart'
  end

  def update
    order_item = OrderItem.find(params[:order_item][:order_item_id])
    if new_quantity > 0
      order_item.update(quantity: new_quantity)
      flash[:notice] = "Quantity updated"
    else
      SessionHandler.new(session).remove_cart_item(order_item)
      flash[:notice] = "Successfully removed <a href=\"/items/#{order_item.item.dao}\">#{order_item.item.name}</a> from your cart."
    end
    redirect_to cart_path
  end

  def destroy
    OrderItem.where(id: session[:cart]).destroy_all
    session.delete(:cart)
    flash[:notice] = "Cart deleted!"
    redirect_to cart_path
  end

  private

    def new_quantity
      if params[:commit] == "Update Quantity"
        params[:order_item][:quantity].to_i
      elsif params[:commit] == "Remove"
        0
      end
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all.order(:name)
    @random_joke = Joke.all.sample
  end

  def show
    @item = Item.find_by_dao(params[:id])
  end
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  def index
    @jokes = Joke.all
  end
end

app/helpers/ajokes_helper.rb
module AjokesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash_alert.html.erb
<div class="row">
  <div class="col-md-12">
    <div class='well'>
      <div class="flash flash-alert"><%= flash.alert %></div>
    </div>
  </div>
</div>

app/views/layouts/_flash_notice.html.erb
<div class="row">
  <div class="col-md-12">
    <div class='well'>
      <div class="flash flash-notice"><%= raw(flash.notice) %></div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class='dad-header'>

  <div class='hit-me-response'><h1>Dad Jokes For Days</h1></div>
  <%= form_for :ajax_joke, url: "/ajax-joke", remote: true do |f| %>
    <%= f.submit "Hit Me!", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/_item.html.erb
<li> <%= link_to item.name, item_path(item), class: "item-title" %><span class='add_to_cart_button'> <%= button_to "Add To Cart", cart_path(item_id: item), class:'btn btn-primary' %></span></li>

app/views/layouts/_joke.html.erb
<div class="container-fluid">
  <div class="row dad-joke-row">
    <div class="col-md-14">
      <div class="well">
        <div class="panel-body">
        <div class="joke-header joke-heading">Current chosen Dad Joke: </div>
        <strong class="joke-header joke-lead"><%= current_joke.lead %> ... <%= current_joke.punchline %></strong>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top header">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Dad Jokes For Days</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Product Categories<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Categories", categories_path, id: "all-categories" %></li>
            <li role="separator" class="divider"></li>
            <% @categories.each do |category| %>
              <li><%= link_to category.name, category_path(category) %></li>
            <% end %>
          </ul>
        </li>

        <li><%= link_to "All Products", items_path %></li>

        <% if current_user %>
          <% if current_user.admin? %>
            <li><%= link_to "Admin Dashboard", admin_dashboard_path %></li>
          <% end %>
          <li><%= link_to "Logged in as #{current_user.user_name}", dashboard_path %></li>
          <li><%= link_to "Logout", logout_path, method: :delete %>
        <% else %>
          <li><%= link_to "Create Account", "/register" %></li>
          <li><a href='/login'>Login</a></li>
        <% end %>
        <li><a href="/cart">Cart</a></li>

      </ul>

    </div><!-- /.navbar-collapse -->


  </div><!-- /.container-fluid -->
<div class='well dad-current-joke'>
  <% if current_joke %>
    <%= current_joke.lead %> ... <%= current_joke.punchline %>
  <% else %>
  <% end %>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DadJokesForDays</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>


  <div class="container">
    <div class="row dad-nav-spacer"> </div>
    <% if flash.alert %>
      <%= render 'layouts/flash_alert' %>
    <% end %>
    
    <% if flash.notice %>
      <%= render 'layouts/flash_notice' %>
    <% end %>
    
    <%= yield %>
  </div>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/partials/_link_summary.html.erb
<%= link_to summary.name, summary, class: 'item-title' %><br>
<%= link_to image_tag(summary.image_url, class: "img-responsive"), summary %><br>